pipeline {
    agent any
    environment {
        MAJOR_VERSION = 1
        MINOR_VERSION = 0
        PATCH_VERSION = 0
    }

    stages {
        stage('Build') {
            steps {
                cleanWs()
                sh '''
                    MAJOR_VERSION=$(<auth_services/tags_folder/major_version.txt)
                    MINOR_VERSION=$(<auth_services/tags_folder/minor_version.txt)
                    PATCH_VERSION=$(<auth_services/tags_folder/patch_version.txt)
                    PATCH_VERSION=$(( PATCH_VERSION + 1))
                '''
                echo "$MAJOR_VERSION"
                echo "$MINOR_VERSION"
                echo "$PATCH_VERSION"
            }
        }
        stage('Push') {
            steps {
                sh '''
                    mkdir build
                    touch build/laptop.txt
                    echo 'Really cooll' >> build/laptop.txt
                '''
            }
        }
        stage('TestFile') {
            steps {
                echo 'Test for file presence'
                sh 'test -f  build/laptop.txt'
            }
        }
    }
    post {
        success {
            archiveArtifacts artifacts: 'build/**'
        }
    }
}






// pipeline {
//     agent any
//     environment {
//         FILE_NAME = 'computer.txt'
//     }

//     stages {
//         stage('Hello') {
//             steps {
//                 cleanWs()
//                 echo 'Hello World!!'
//                 echo 'Updated Jenkins webhook security'
//                 echo "The file name is $FILE_NAME"
//             }
//         }
//         stage('WriteFile') {
//             steps {
//                 sh '''
//                     mkdir build
//                     touch build/laptop.txt
//                     echo 'Really cool' >> build/laptop.txt
//                 '''
//             }
//         }
//         stage('TestFile') {
//             steps {
//                 echo 'Test for file presence'
//                 sh 'test -f  build/laptop.txt'
//             }
//         }
//     }
//     post {
//         success {
//             archiveArtifacts artifacts: 'build/**'
//         }
//     }
// }
