pipeline {
    agent any
    environment {
        MAJOR_VERSION = 1
        MINOR_VERSION = 0
        PATCH_VERSION = 0
        DOCKER_CRIDENTIALS_ID = 'dockerhub-jenkins'
        DOCKER_REGISTRY = 'https://hub.docker.com/u/doneze'
        DOCKER_HUB_REPO = 'doneze/auth'
        TAG = '1.0.43'
    }

    stages {
        stage('Build') {
            steps {
                cleanWs()
                sh '''
                    mkdir -p tags_folder
                    touch tags_folder/major_version.txt
                    touch tags_folder/minor_version.txt
                    touch tags_folder/patch_version.txt
                    echo '2' >> tags_folder/major_version.txt
                    echo '4' >> tags_folder/minor_version.txt
                    echo '6' >> tags_folder/patch_version.txt
                    MAJOR_VERSION=$(cat tags_folder/major_version.txt)
                    MINOR_VERSION=$(cat tags_folder/minor_version.txt)
                    PATCH_VERSION=$(cat tags_folder/patch_version.txt)
                    PATCH_VERSION=$(( PATCH_VERSION + 1))
                    echo "$MAJOR_VERSION"
                    echo "$MINOR_VERSION"
                    echo "$PATCH_VERSION"
                '''
                echo "$MAJOR_VERSION"
                echo "$MINOR_VERSION"
                echo "$PATCH_VERSION"
            }
        }
        stage('Checkout Code') {
            steps {
                git url: 'https://github.com/Dezeabasili/hotel_kubernetes.git', branch: 'main', credentials: 'github-cred'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("$DOCKER_HUB_REPO:$TAG", 'auth_services')
                }
            }
        }
        stage('Push To Docker') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', "$DOCKER_CRIDENTIALS_ID") {dockerImage.push("$TAG")}
                }
            }
        }
        stage('Leave this for now') {
            steps {
                sh '''
                    mkdir -p build
                    touch build/laptop.txt
                    echo 'Really cools' >> build/laptop.txt
                '''
            }
        }
    }
    post {
        success {
            archiveArtifacts artifacts: 'build/**'
        }
    }
}







// pipeline {
//     agent any
//     environment {
//         FILE_NAME = 'computer.txt'
//     }

//     stages {
//         stage('Hello') {
//             steps {
//                 cleanWs()
//                 echo 'Hello World!!'
//                 echo 'Updated Jenkins webhook security'
//                 echo "The file name is $FILE_NAME"
//             }
//         }
//         stage('WriteFile') {
//             steps {
//                 sh '''
//                     mkdir build
//                     touch build/laptop.txt
//                     echo 'Really cool' >> build/laptop.txt
//                 '''
//             }
//         }
//         stage('TestFile') {
//             steps {
//                 echo 'Test for file presence'
//                 sh 'test -f  build/laptop.txt'
//             }
//         }
//     }
//     post {
//         success {
//             archiveArtifacts artifacts: 'build/**'
//         }
//     }
// }
